name: PunishmentsGUI
version: '${project.version}'
main: me.ivanlpc.punishmentsgui.PunishmentsGUI
softdepend: [LiteBans]
commands:
  punish:
    description: Opens a GUI to punish the player
    aliases: [gestionar, punishmentsgui]
