name: PunishmentsCore
version: '${project.version}'
main: me.ivanlpc.punishmentscore.PunishmentsCore
depend: [LiteBans]
commands:
  punish:
    description: Opens a GUI to punish the player
    aliases: [gestionar, pn]
  orders:
    description: Opens a GUI with pending punishments
    aliases: [pedidos, pedi2, orders]